### ISSUE TITLE
Getting error sklearn.externals.joblib'

### ISSUE THREAD

**Issue by AtomicNess123** [neuroquery/pubget#16]
I am getting the error:

`ModuleNotFoundError: No module named 'sklearn.externals.joblib'`

When running

`pubget download -q "fMRI[Title] AND (2019[PubDate] : 2019[PubDate])" pubget_data       `

How to fix this bug?
Thanks!

**Comment by jeromedockes** [comment]
Hello, thank you for reporting this problem!

sklearn.externals.joblib does not exist anymore in recent versions of
scikit-learn; could you try upgrading scikit-learn and joblib?

pip install -U scikit-learn joblib

Otherwise, could you please provide the full traceback (the complete
error message) so that I know where the error arises?

thank you!
